# Generated by Django 4.1.3 on 2022-11-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(null=True, upload_to="ads"),
        ),
    ]
