# Generated by Django 4.1.3 on 2022-11-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="ads.ad",
                verbose_name="Объявление",
            ),
        ),
    ]
